import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { TableProvider } from "./_contexts/TableContext";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600"],
});

export const metadata = {
  title: "InnoNex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <TableProvider>
          <Toaster
            toastOptions={{
              duration: 2000,
              style: {
                background: "linear-gradient(to right, #4caf50, #81c784)", // Green gradient background
                color: "#fff", // White text
                fontWeight: "500",
                fontSize: "16px",
                borderRadius: "8px",
                boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15)",
              },
              success: {
                style: {
                  background: "linear-gradient(to right, #66bb6a, #43a047)", // Success-specific background
                },
                icon: "🟢",
              },
              error: {
                style: {
                  background: "linear-gradient(to right, #e57373, #f44336)", // Error-specific background
                },
                icon: "❌",
              },
            }}
          />
          {children}
        </TableProvider>
      </body>
    </html>
  );
}
